

FROM mcr.microsoft.com/devcontainers/python:3.10

# Puedes añadir cualquier paso de configuración adicional si es necesario
# Por ejemplo, instalar paquetes de sistema, etc.
# RUN apt-get update && apt-get install -y some-package